apiVersion: v2
name: argilla
description: A Helm chart for deploying the Argilla server and worker.
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: redis
    version: "17.0.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
