apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argilla.fullname" . }}-worker
  labels:
    {{- include "argilla.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argilla.name" . }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argilla.name" . }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Use the command to start the worker process, passing the BACKGROUND_NUM_WORKERS variable.
          command: [ "sh", "-c", "python -m argilla_server worker --num-workers ${BACKGROUND_NUM_WORKERS}" ]
          env:
            - name: ARGILLA_HOME_PATH
              value: {{ .Values.env.ARGILLA_HOME_PATH | quote }}
            - name: ARGILLA_ELASTICSEARCH
              value: {{ .Values.env.ARGILLA_ELASTICSEARCH | quote }}
            - name: ARGILLA_DATABASE_URL
              value: {{ .Values.env.ARGILLA_DATABASE_URL | quote }}
            - name: ARGILLA_REDIS_URL
              value: {{ .Values.env.ARGILLA_REDIS_URL | quote }}
            - name: BACKGROUND_NUM_WORKERS
              value: {{ .Values.worker.BACKGROUND_NUM_WORKERS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}