apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic.fullname" . }}
  labels:
    {{- include "basic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "basic.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "basic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.servicePort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}

          env:
            {{- toYaml .Values.config.envVars | nindent 12 }}